services:
  playz-camera-api:
    build: .
    image: playz-camera-api
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/vc/:/opt/vc/:ro
    devices:
      - /dev/vchiq
      - /dev/vcsm
      - /dev/vcsm-cma