version: '3'
services:
  playz-camera-api:
    build: .
    image: playz-camera-api
    command: ["--module-id", "01"]
    restart: always
    volumes:
      - /opt/vc/:/opt/vc/:ro
    ports:
      - "80:8080"
    devices:
      - /dev/vchiq
      - /dev/vcsm
      - /dev/vcsm-cma